package com.k2.Html5Builder;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Logger;

import com.k2.Html5Builder.elements.HtmlBody;
import com.k2.Html5Builder.elements.HtmlDiv;
import com.k2.Html5Builder.elements.HtmlHead;
import com.k2.Html5Builder.elements.HtmlP;
import com.k2.Html5Builder.elements.HtmlSection;
import com.k2.Html5Builder.elements.attrValues.Target;

public class BasicExample {

	public static void main(String[] args) throws FileNotFoundException {

		Html5Builder hb = new Html5Builder().setIndent("  ").setWarngingLog(Logger.getLogger("Html Builder Warning"));
		
		hb.page()
			.head
				.title("Sample page generatd by Html5Builder")
				.author("Simon Emmott")
				.description("This page is a sample page generated by the Html5builder")
				.keywords("Html5Builder", "Example")
				.up(HtmlPage.class)
			.body
				.section()
					.h().text("Html5Builder sample page").up(HtmlSection.class)
					.div()
						.p().text("The example shows a very simple page generated using the Html5Builder").up(HtmlDiv.class)
						.p()
							.text("For more details on the Html5Builder please see the Github project ")
							.a().setHref("https://github.com/simonemmott/Html5Builder").text("Html5Builder").up(HtmlP.class)
							.text(" or the Html5Builders ")
							.a().setHref("https://simonemmott.github.io/Html5Builder/javadoc/").text("javadoc").page()
		.toHtml(new File("docs/sample.html"));

	}

}
